### ISSUE TITLE
Mod can't be installed due to :compileApiJava error

### ISSUE THREAD

**Issue by ToonLucas22** [KJ4IPS/Hackery#17]
See this image
![gradle error](https://cloud.githubusercontent.com/assets/10928948/8150357/5a14f746-12b4-11e5-8c46-61027ac891e9.png)

**Comment by Laikulo** [comment]
If you just want to play with the current version, grab a jar from here: http://ci.jam-craft.net/job/Hackery/

As far as the failure, you don't seem to have the java compiler installed (or it is not in PATH or JAVA_HOME)
